name: Edith Shao
# markdown: redcarpet
highlighter: rouge
# add any customized folder
include:
  - _files
# display dynamic modified dates
plugins:
  - jekyll-sitemap

site:
  - about: _posts/2019-1-14-About-Me.md
